/**
 * @author Brooks Johnson
 */

public with sharing class IntroToSOQL {

    public static void simpleQuery(){
        //Basic SOQL Syntax



    }

    public static void childToParent(){
        //SOQL syntax to get data from a child's parent record

    }

    public static void parentToChild(){
        //SOQL syntax to query a parent to child relationship


    }

    public static void customObjectsQuery(){
        //SOQL syntax to query a custom object relationship
    }

}