public with sharing class Primitives {
    //Blob -For Webservices and Crypto
    //Boolean
    //Date
    //DateTime
    //Decimal - 32 bit
    //Double - 64 bit
    // Id
    // Integer -32 bit
    //Long -64 bit
    //Object
    //String

    //Apex is a statically typed case insensitive language

    public static void primitiveDataTypes(Boolean doCalc, Integer num1, Integer num2){
        if (doCalc) {
            System.debug(num1 + num2);
        }



    }







}